### ISSUE TITLE
Getting a reference data on success

### ISSUE THREAD

**Issue by Onyelaudochukwuka** [PaystackOSS/sample-react#27]
Is there a way to get a reference data containing the transaction details on success ?

**Comment by tolu-paystack** [comment]
Hey @Onyelaudochukwuka I just updated the sample to show an alert with the transaction reference after a successful transaction. 

Check out [line 27](https://github.com/PaystackOSS/sample-react/blob/master/src/App.js#L27) of App.js to see how you can get the reference
